learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Specifies URL schemes for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Topics page
    path('topics/', views.topics, name='topics'),
    # Page with topics' data
    path('topics/<int:topic_id>/', views.topic, name='topic')
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """Topic for user"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Learned information by user"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Returns a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}"
        else:
            return self.text

learning_logs/views.py
from pydoc_data.topics import topics
import re
from django.shortcuts import render
from .models import Topic

# Create your views here.
def index(request):
    """Learning Log app homepage"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Shows topics list"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Shows topic's tread"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Learning Log</title>
        <style>
                .description {
                        margin: 10px;
                        padding: 5px;
                      
                }

                .navigation {
                    background-color: rgb(250, 250, 210);
                    padding: 10px;
                    font-size: 20px;
                }
        </style>
</head>
<body>
    <nav class="navigation">
        <a href="{% url 'learning_logs:index' %}">Learning log</a> -
        <a href="{% url 'learning_logs:topics' %}">Topics</a>
    </nav>
</body>
{% block content %}{% endblock content%}

learning_logs/templates/learning_logs/index.html
        {% extends "learning_logs/base.html" %}
{% block content %}
<section class="description">
        <article>Learning Log helps you keep track of your learning, for any topic you're
                learning about.
        </article>        
</section>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
 
{% block content %}

<h2>Topic: {{ topic }}</h2>

<article>
    <h3>Entries</h3>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>    
    {% empty %}
        <li>
            There are no entries for this topic yet.
        </li>
    {% endfor %}    
    </ul>
</article>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<h2>Topics</h2>

<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}